"""add business_id to appointments

Revision ID: c1aa5729715a
Revises: e9cf43f4e54f
Create Date: 2026-07-21 14:16:49.496276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1aa5729715a'
down_revision: Union[str, Sequence[str], None] = 'e9cf43f4e54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('business_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'business', ['business_id'], ['id'])
    op.alter_column('customers', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'business_id')
    # ### end Alembic commands ###
