"""changed phone field to phone_number in customer table

Revision ID: e9cf43f4e54f
Revises: 51dee62b4d52
Create Date: 2026-07-16 15:21:07.811427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9cf43f4e54f'
down_revision: Union[str, Sequence[str], None] = '51dee62b4d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'customers',
        'phone',
        new_column_name='phone_number',
        existing_type=sa.String(length=20),
        existing_nullable=False,
    )
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.alter_column(
        'customers',
        'phone_number',
        new_column_name='phone',
        existing_type=sa.String(length=20),
        existing_nullable=False,
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    # ### end Alembic commands ###
